// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type InventorySymbol struct {
	Symbolid int64
	Symbol   string
}

type Price struct {
	Symbolid   int64
	TradingDay time.Time
	Open       float64
	Close      float64
	Delta      sql.NullFloat64
	PctDelta   sql.NullFloat64
}

type WeeklyPrice struct {
	Symbolid  int64
	WeekStart time.Time
	Open      float64
	Close     float64
	Delta     sql.NullFloat64
	PctDelta  sql.NullFloat64
}
